name = "NTS Academic Theme"
license = "MIT"
licenselink = "https://github.com/yourhandle/ntstheme/blob/main/LICENSE"
description = "A minimalistic academic theme for Hugo"
homepage = "https://github.com/yourhandle/ntstheme"
demosite = "https://yoursite.com"
tags = ["academic", "minimal", "responsive", "blog", "research"]
features = ["responsive", "math", "syntax highlighting", "SEO"]
min_version = "0.116.0"

[author]
name = "Your Name"
homepage = "https://yoursite.com"

baseURL = 'https://example.org/'
languageCode = 'en-US'
title = 'notesbyts'

[menus]
[[menus.main]]
name = 'Home'
pageRef = '/'
weight = 10

[[menus.main]]
name = 'Publications'
pageRef = '/publications'
weight = 20

[[menus.main]]
name = 'Projects'
pageRef = '/projects'
weight = 30

[[menus.main]]
name = 'Blog'
pageRef = '/blog'
weight = 40

[[menus.main]]
name = 'About'
pageRef = '/about'
weight = 50

[module]
[module.hugoVersion]
extended = false
min = '0.146.0'
